
### **1. What are data structures, and why are they important?**

**Data structures** are ways to organize and store data in a computer so that it can be accessed and modified efficiently. They're important because they help solve problems effectively and influence the performance of algorithms.

---

### **2. Explain the difference between mutable and immutable data types with examples.**

* **Mutable**: Can be changed after creation.
  Example: `list = [1, 2, 3] → list[0] = 9`
* **Immutable**: Cannot be changed once created.
  Example: `string = "hello" → string[0] = 'H'` ❌ (This causes an error)

---

### **3. What are the main differences between lists and tuples in Python?**

| Feature     | List            | Tuple               |
| ----------- | --------------- | ------------------- |
| Mutability  | Mutable         | Immutable           |
| Syntax      | `[]`            | `()`                |
| Performance | Slightly slower | Faster (fixed size) |
| Use Case    | Changing data   | Constant data       |

---

### **4. Describe how dictionaries store data.**

Dictionaries store data as **key-value pairs**. Each key is unique and acts like a label to access its value. Internally, they use **hash tables** to map keys to values efficiently.

---

### **5. Why might you use a set instead of a list in Python?**

* To **remove duplicates** automatically
* To check **membership faster** (O(1) average)
* To perform set operations like union, intersection, etc.

---

### **6. What is a string in Python, and how is it different from a list?**

A **string** is a sequence of characters, **immutable**, and often used to represent text. A **list** is a mutable sequence that can contain **any data type**.
Example:

```python
string = "hello"
list = ['h', 'e', 'l', 'l', 'o']
```

---

### **7. How do tuples ensure data integrity in Python?**

Tuples are **immutable**, which means once created, their values can't be changed. This prevents accidental modification, making them suitable for **read-only** or **secure** data.

---

### **8. What is a hash table, and how does it relate to dictionaries in Python?**

A **hash table** is a data structure that maps **keys to values** using a hash function. Python dictionaries use hash tables under the hood for **fast lookup, insertion, and deletion**.

---

### **9. Can lists contain different data types in Python?**

Yes, Python lists are **heterogeneous**. Example:

```python
mixed_list = [1, "hello", 3.14, True]
```

---

### **10. Explain why strings are immutable in Python.**

Strings are immutable to:

* Enhance **security**
* Allow **hashing** (used as dictionary keys)
* Enable **memory optimization** by reusing objects

---

### **11. What advantages do dictionaries offer over lists for certain tasks?**

* **Faster lookup** by key (O(1) average)
* More **meaningful indexing** using keys instead of positions
* Ideal for **structured data** (like a person’s name, age, etc.)

---

### **12. Describe a scenario where using a tuple would be preferable over a list.**

When storing fixed, **read-only** data like days of the week:

```python
days = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")
```

---

### **13. How do sets handle duplicate values in Python?**

Sets **automatically remove duplicates**. Example:

```python
set([1, 2, 2, 3]) → {1, 2, 3}
```

---

### **14. How does the `in` keyword work differently for lists and dictionaries?**

* In **lists**, `in` checks for **values**.
* In **dictionaries**, `in` checks for **keys**.
  Example:

```python
3 in [1, 2, 3] → True  
"age" in {"age": 25} → True
```

---

### **15. Can you modify the elements of a tuple? Explain why or why not.**

No, tuples are **immutable**, so their elements cannot be changed after creation. This ensures **data safety** in fixed records.

---

### **16. What is a nested dictionary, and give an example of its use case.**

A **nested dictionary** is a dictionary inside another dictionary.
**Use Case**: Storing student data by ID

```python
students = {
    101: {"name": "Alice", "age": 20},
    102: {"name": "Bob", "age": 22}
}
```

---

### **17. Describe the time complexity of accessing elements in a dictionary.**

**Average case**: O(1) – Constant time due to hashing
**Worst case**: O(n) – Rare, due to hash collisions

---

### **18. In what situations are lists preferred over dictionaries?**

* When order matters
* When you don’t need key-value pairs
* For simple collections like a list of names

---

### **19. Why are dictionaries considered unordered, and how does that affect data retrieval?**

Before Python 3.7, dictionaries didn’t maintain insertion order. Since 3.7, they preserve order, but still **don’t rely on position** like lists. Retrieval is based on **keys**, not order.

---

### **20. Explain the difference between a list and a dictionary in terms of data retrieval.**

* **List**: Access by **index/position**
  Example: `my_list[0]`
* **Dictionary**: Access by **key**
  Example: `my_dict["name"]`

In [3]:
#1. Write a code to create a string with your name and print it
name = "Samanshi"
print("My name is", name)

My name is Samanshi

In [5]:
#2. Write a code to find the length of the string "Hello World"
text = "Hello World"
length = len(text)
print("Length of the string is:", length)

Length of the string is: 11

In [6]:
#3. Write a code to slice the first 3 characters from the string "Python Programming".
text = "Python Programming"
sliced_text = text[:3]
print("First 3 characters are:", sliced_text)

First 3 characters are: Pyt

In [7]:
#4. Write a code to convert the string "hello" to uppercase.
text = "hello"
uppercase_text = text.upper()
print("Uppercase text is:", uppercase_text)

Uppercase text is: HELLO

In [8]:
#5. Write a code to replace the word "apple" with "orange" in the string "I like apple".
string = "I like apple"
new_string = string.replace("apple", "orange")
print(new_string)

I like orange

In [9]:
#6. Write a code to create a list with numbers 1 to 5 and print it.
numbers = [1, 2, 3, 4, 5]
print(numbers)

[1, 2, 3, 4, 5]

In [10]:
#7. Write a code to append the number 10 to the list [1, 2, 3, 4].
my_list = [1, 2, 3, 4]
my_list.append(10)
print(my_list)

[1, 2, 3, 4, 10]

In [11]:
#8. Write a code to remove the number 3 from the list [1, 2, 3, 4, 5].
my_list = [1, 2, 3, 4, 5]
my_list.remove(3)
print(my_list)

[1, 2, 4, 5]

In [12]:
#9. Write a code to access the second element in the list ['a', 'b', 'c', 'd'].
my_list = ['a', 'b', 'c', 'd']
second_element = my_list[1]
print(second_element)

b

In [13]:
#10. Write a code to reverse the list [10, 20, 30, 40, 50].
my_list = [10, 20, 30, 40, 50]
reversed_list = my_list[::-1]
print(reversed_list)

[50, 40, 30, 20, 10]

In [14]:
#11. Write a code to create a tuple with the elements 100, 200, 300 and print it.
tuple1 = (100, 200, 300)
print(tuple1)

(100, 200, 300)

In [15]:
#12. Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow').
tuple1 = ('red', 'green', 'blue', 'yellow')
second_last_element = tuple1[-2]
print(second_last_element)

blue

In [16]:
#13. Write a code to find the minimum number in the tuple (10, 20, 5, 15).
tuple1 = (10, 20, 5, 15)
min_number = min(tuple1)
print(min_number)

5

In [17]:
#14. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').
tuple1 = ('dog', 'cat', 'rabbit')
index = tuple1.index('cat')
print(index)

1

In [18]:
#15.  Write a code to create a tuple containing three different fruits and check if "kiwi" is in it.
fruits = ("apple", "banana", "cherry")
if "kiwi" in fruits:
    print("kiwi is in the tuple")
else:
    print("kiwi is not in the tuple")

kiwi is not in the tuple

In [20]:
#16. Write a code to create a set with the elements 'a', 'b', 'c' and print it.
set = {'a', 'b', 'c'}
print(set)

{'a', 'b', 'c'}

In [21]:
#17. Write a code to clear all elements from the set {1, 2, 3, 4, 5}.
my_set = {1, 2, 3, 4, 5}
my_set.clear()
print(my_set)

set()

In [22]:
#18.  Write a code to remove the element 4 from the set {1, 2, 3, 4}
my_set = {1, 2, 3, 4}
my_set.remove(4)
print(my_set)

{1, 2, 3}

In [23]:
#19.  Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}.
set1 = {1, 2, 3}
set2 = {3, 4, 5}
union_set = set1.union(set2)
print(union_set)

{1, 2, 3, 4, 5}

In [24]:
#20. Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}
set1 = {1, 2, 3}
set2 = {2, 3, 4}
intersection_set = set1.intersection(set2)
print(intersection_set)

{2, 3}

In [25]:
#21.  Write a code to create a dictionary with the keys "name", "age", and "city", and print it.
my_dict = {
    "name": "Samanshi",
    "age": 18,
    "city": "New Delhi"
}
print(my_dict)

{'name': 'Samanshi', 'age': 18, 'city': 'New Delhi'}

In [26]:
#22. Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}.
my_dict = {'name': 'John', 'age': 25}
my_dict['country'] = 'USA'
print(my_dict)

{'name': 'John', 'age': 25, 'country': 'USA'}

In [27]:
#23.  Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}.
my_dict = {'name': 'Alice', 'age': 30}
name_value = my_dict['name']
print(name_value)

Alice

In [28]:
#24.  Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}.
my_dict = {'name': 'Bob', 'age': 22, 'city': 'New York'}
del my_dict['age']
print(my_dict)
#

{'name': 'Bob', 'city': 'New York'}

In [29]:
#25. Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}.
my_dict = {'name': 'Alice', 'city': 'Paris'}
if 'city' in my_dict:
    print("Key 'city' exists in the dictionary")
else:
    print("Key 'city' does not exist in the dictionary")

Key 'city' exists in the dictionary

In [64]:
#26. Write a code to create a list, a tuple, and a dictionary, and print them all.
my_list = [1, 2, 3, 4, 5]
my_tuple = (10, 20, 30, 40, 50)
my_dict = {'name': 'Alice', 'age': 25}

In [32]:
#27. Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the
#result.(replaced)
import random
random_numbers = [random.randint(1, 100) for _ in range(5)]
random_numbers.sort()
print("Sorted list of random numbers:", random_numbers)

Sorted list of random numbers: [8, 25, 40, 88, 96]

In [35]:
#28.  Write a code to create a list with strings and print the element at the third index.
my_list = ["apple", "banana", "cherry", "date", "elderberry"]
third_element = my_list[2]
print("Element at index 2:", third_element)

Element at index 2: cherry

In [36]:
#29. Write a code to combine two dictionaries into one and print the result.
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
combined_dict = {**dict1, **dict2}
print("Combined dictionary:", combined_dict)

Combined dictionary: {'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [55]:
#30. Write a code to convert a list of strings into a set.
string_list = ["apple", "banana", "apple", "cherry", "banana"]
string_set = (string_list)
print("Set of strings:", string_set)

Set of strings: ['apple', 'banana', 'apple', 'cherry', 'banana']